<?php
/**
 * Aplicador de cambios — Proyecto iteradores (PHP).
 *
 * Tanda V1.5piloto.76q (Fase B2.1: crear los compartidos por terminal).
 * Corrección: §12 ancla sobre el bullet v76n (no existe bullet v76p en §12).
 *
 * Uso: php aplicar_cambios.php
 */

$modo_estricto = true;
$raiz_proyecto = __DIR__;

$cambios = [

    // ============================================================
    // Aplicacion/Migraciones/Comandos.php — nuevo comando
    // ============================================================

    [
        'tipo' => 'reemplazar',
        'archivo' => 'Aplicacion/Migraciones/Comandos.php',
        'descripcion' => 'Comandos: agregar app:crear_compartidos_terminal',
        'buscar' => [
            '        return [\'exito\' => true];',
            '    }, null, false);',
            '}',
            '',
            '/**',
            ' * Devuelve el nodo contenedor aplicacion/migraciones, o null.',
        ],
        'reemplazar' => [
            '        return [\'exito\' => true];',
            '    }, null, false);',
            '',
            '    // ─── app:crear_compartidos_terminal ─────────────────',
            '    //',
            '    // Fase B2.1 del modelo topológico (v76q).',
            '    //',
            '    // Crea el contenedor `compartido_con_us_termX` en cada',
            '    // dueño, uno por cada terminal autorizado en algún viaje',
            '    // del dueño. Estructura del compartido:',
            '    //',
            '    //   us_duenoY/compartido_con_us_termX   (dato=nombre_dueno)',
            '    //   ├── viajes        → solo los autorizados a termX',
            '    //   ├── empresas      → las referenciadas por esos viajes',
            '    //   ├── pasajeros     → alias al contenedor privado del dueño',
            '    //   ├── ventas        → las ventas de termX',
            '    //   ├── cancelaciones → las cancelaciones de termX',
            '    //   └── terminales    → solo us_termX',
            '    //',
            '    // No toca los enlaces viejos: los compartidos coexisten',
            '    // con la estructura actual. El código sigue usando la raíz',
            '    // `usuarios` como hoy. El repuntado es Fase B2.2/B2.3.',
            '    //',
            '    // Args: [\'dueno\' => nombre | \'todos\',',
            '    //        \'terminal\' => nombre | \'todos\']',
            '    // Devuelve: { creados: int, salteados: int, errores: [] }.',
            '    Controlador::registrar_comando(\'app:crear_compartidos_terminal\', function(string $token, array $args) {',
            '        $opciones = $args[0] ?? [];',
            '        $dueno_filtro = (string)($opciones[\'dueno\'] ?? \'todos\');',
            '        $terminal_filtro = (string)($opciones[\'terminal\'] ?? \'todos\');',
            '',
            '        $creados = 0;',
            '        $salteados = 0;',
            '        $errores = [];',
            '',
            '        Nodo::por_cada_nodo_ejecutar($token, function($nodo) use (&$creados, &$salteados, &$errores, $dueno_filtro, $terminal_filtro) {',
            '            $id = (string)$nodo->id();',
            '            if (strpos($id, \'us_\') !== 0) return null;',
            '',
            '            // Nivel: puede estar en la raíz o dentro de `publico`.',
            '            $nivel_nodo = $nodo->adyacente(\'nivel\');',
            '            if (!$nivel_nodo) {',
            '                $publico = $nodo->adyacente(\'publico\');',
            '                if ($publico) $nivel_nodo = $publico->adyacente(\'nivel\');',
            '            }',
            '            $nivel = $nivel_nodo ? $nivel_nodo->dato() : \'\';',
            '            if ($nivel !== \'dueno\') return null;',
            '',
            '            $nombre_dueno = (string)$nodo->dato();',
            '            if ($dueno_filtro !== \'todos\' && $nombre_dueno !== $dueno_filtro) return null;',
            '',
            '            // Obtener contenedor de viajes (raíz o privado).',
            '            $cont_viajes = $nodo->adyacente(\'viajes\');',
            '            if (!$cont_viajes) {',
            '                $priv = $nodo->adyacente(\'privado\');',
            '                if ($priv) $cont_viajes = $priv->adyacente(\'viajes\');',
            '            }',
            '            if (!$cont_viajes) return null;',
            '',
            '            // Recolectar terminales autorizados en algún viaje.',
            '            $ady_viajes = (array)$cont_viajes->adyacentes();',
            '            $terminales_autorizados = [];',
            '            foreach ($ady_viajes as $nv => $nodo_viaje) {',
            '                $tas = $nodo_viaje->adyacente(\'terminales_autorizadas\');',
            '                if (!$tas) continue;',
            '                foreach ((array)$tas->adyacentes() as $nombre_t => $nodo_tv) {',
            '                    $terminales_autorizados[(string)$nombre_t] = true;',
            '                }',
            '            }',
            '            if (empty($terminales_autorizados)) return null;',
            '',
            '            // Otros contenedores del dueño.',
            '            $cont_ventas = $nodo->adyacente(\'ventas\');',
            '            if (!$cont_ventas) {',
            '                $priv = $nodo->adyacente(\'privado\');',
            '                if ($priv) $cont_ventas = $priv->adyacente(\'ventas\');',
            '            }',
            '            $cont_pasajeros = $nodo->adyacente(\'pasajeros\');',
            '            if (!$cont_pasajeros) {',
            '                $priv = $nodo->adyacente(\'privado\');',
            '                if ($priv) $cont_pasajeros = $priv->adyacente(\'pasajeros\');',
            '            }',
            '            $cont_cancelaciones = $nodo->adyacente(\'cancelaciones\');',
            '            if (!$cont_cancelaciones) {',
            '                $priv = $nodo->adyacente(\'privado\');',
            '                if ($priv) $cont_cancelaciones = $priv->adyacente(\'cancelaciones\');',
            '            }',
            '',
            '            foreach (array_keys($terminales_autorizados) as $nombre_terminal) {',
            '                if ($terminal_filtro !== \'todos\' && $nombre_terminal !== $terminal_filtro) continue;',
            '',
            '                $enlace_compartido = \'compartido_con_\' . $nombre_terminal;',
            '',
            '                // Idempotencia: si ya existe, saltear.',
            '                if ($nodo->adyacente($enlace_compartido)) {',
            '                    $salteados++;',
            '                    continue;',
            '                }',
            '',
            '                // Crear contenedor compartido.',
            '                $compartido = Nodo::crear_con_dato($nombre_dueno);',
            '                if (!$compartido) {',
            '                    $errores[] = "No se pudo crear compartido para $nombre_dueno/$nombre_terminal";',
            '                    continue;',
            '                }',
            '                $nodo->_adyacente_en($compartido, $enlace_compartido);',
            '',
            '                // Sub-contenedores. `pasajeros` es alias, se enlaza después.',
            '                $c_viajes = Nodo::crear_con_dato(\'\');',
            '                $c_empresas = Nodo::crear_con_dato(\'\');',
            '                $c_ventas = Nodo::crear_con_dato(\'\');',
            '                $c_cancelaciones = Nodo::crear_con_dato(\'\');',
            '                $c_terminales = Nodo::crear_con_dato(\'\');',
            '',
            '                $compartido->_adyacente_en($c_viajes, \'viajes\');',
            '                $compartido->_adyacente_en($c_empresas, \'empresas\');',
            '                $compartido->_adyacente_en($c_ventas, \'ventas\');',
            '                $compartido->_adyacente_en($c_cancelaciones, \'cancelaciones\');',
            '                $compartido->_adyacente_en($c_terminales, \'terminales\');',
            '',
            '                if ($cont_pasajeros) {',
            '                    $compartido->_adyacente_en($cont_pasajeros, \'pasajeros\');',
            '                }',
            '',
            '                // Llenar viajes + recolectar empresas referenciadas.',
            '                $empresas_ref = [];',
            '                foreach ($ady_viajes as $nv => $nodo_viaje) {',
            '                    $tas = $nodo_viaje->adyacente(\'terminales_autorizadas\');',
            '                    if (!$tas || !$tas->adyacente($nombre_terminal)) continue;',
            '',
            '                    $c_viajes->_adyacente_en($nodo_viaje, (string)$nv);',
            '',
            '                    $micros = $nodo_viaje->adyacente(\'micros\');',
            '                    if ($micros) {',
            '                        foreach ((array)$micros->adyacentes() as $nodo_micro) {',
            '                            $emp = $nodo_micro->adyacente(\'empresa\');',
            '                            if ($emp) $empresas_ref[(string)$emp->dato()] = $emp;',
            '                        }',
            '                    }',
            '                }',
            '',
            '                // Llenar empresas.',
            '                foreach ($empresas_ref as $ne => $nodo_e) {',
            '                    $c_empresas->_adyacente_en($nodo_e, (string)$ne);',
            '                }',
            '',
            '                // Llenar ventas del terminal (árbol hmi/hd).',
            '                if ($cont_ventas) {',
            '                    $actual = hmi($cont_ventas);',
            '                    $seg = 0;',
            '                    while ($actual && $seg < 3000) {',
            '                        $nt = $actual->adyacente(\'terminal\');',
            '                        if ($nt && $nt->dato() === $nombre_terminal) {',
            '                            $c_ventas->_adyacente_en($actual, (string)$actual->id());',
            '                        }',
            '                        $actual = hd($actual);',
            '                        $seg++;',
            '                    }',
            '                }',
            '',
            '                // Llenar cancelaciones del terminal.',
            '                if ($cont_cancelaciones) {',
            '                    $actual = hmi($cont_cancelaciones);',
            '                    $seg = 0;',
            '                    while ($actual && $seg < 3000) {',
            '                        $nt = $actual->adyacente(\'terminal\');',
            '                        if ($nt && $nt->dato() === $nombre_terminal) {',
            '                            $c_cancelaciones->_adyacente_en($actual, (string)$actual->id());',
            '                        }',
            '                        $actual = hd($actual);',
            '                        $seg++;',
            '                    }',
            '                }',
            '',
            '                // Llenar terminales: solo el propio.',
            '                $raiz = Nodo::nodo_por_id(\'usuarios\');',
            '                $nodo_term = $raiz ? $raiz->adyacente($nombre_terminal) : null;',
            '                if ($nodo_term) {',
            '                    $c_terminales->_adyacente_en($nodo_term, $nombre_terminal);',
            '                }',
            '',
            '                $creados++;',
            '            }',
            '            return null;',
            '        }, null);',
            '',
            '        return [\'creados\' => $creados, \'salteados\' => $salteados, \'errores\' => $errores];',
            '    }, null, false);',
            '}',
            '',
            '/**',
            ' * Devuelve el nodo contenedor aplicacion/migraciones, o null.',
        ],
    ],

    // ============================================================
    // Aplicacion/Migraciones/Funciones.php — detección + aplicación
    // ============================================================

    [
        'tipo' => 'reemplazar',
        'archivo' => 'Aplicacion/Migraciones/Funciones.php',
        'descripcion' => 'Funciones: detección y aplicación de compartidos',
        'buscar' => [
            'function aplicar_migracion_niveles_usuario(string $token): array {',
            '    $res = Controlador::ejecutar_comando(\'grafo:crear_niveles_usuario\', [\'usuario\' => \'todos\']);',
            '    if (!is_array($res)) {',
            '        return [\'exito\' => false, \'detalles\' => [\'El comando no devolvió un resumen válido.\']];',
            '    }',
            '    if (!empty($res[\'errores\'])) {',
            '        return [\'exito\' => false, \'detalles\' => $res];',
            '    }',
            '    return [\'exito\' => true, \'detalles\' => $res];',
            '}',
            '?>',
        ],
        'reemplazar' => [
            'function aplicar_migracion_niveles_usuario(string $token): array {',
            '    $res = Controlador::ejecutar_comando(\'grafo:crear_niveles_usuario\', [\'usuario\' => \'todos\']);',
            '    if (!is_array($res)) {',
            '        return [\'exito\' => false, \'detalles\' => [\'El comando no devolvió un resumen válido.\']];',
            '    }',
            '    if (!empty($res[\'errores\'])) {',
            '        return [\'exito\' => false, \'detalles\' => $res];',
            '    }',
            '    return [\'exito\' => true, \'detalles\' => $res];',
            '}',
            '',
            '// ============================================================',
            '// COMPARTIDOS POR TERMINAL (Fase B2.1, v76q)',
            '// ============================================================',
            '',
            '/**',
            ' * ¿Todos los terminales autorizados en algún viaje tienen',
            ' * su contenedor `compartido_con_*` en el dueño?',
            ' *',
            ' * @param string $token',
            ' * @return bool',
            ' */',
            'function detectar_compartidos_terminal(string $token): bool {',
            '    $todos_ok = true;',
            '    Nodo::por_cada_nodo_ejecutar($token, function($nodo) use (&$todos_ok) {',
            '        if (!$todos_ok) return null;',
            '        $id = (string)$nodo->id();',
            '        if (strpos($id, \'us_\') !== 0) return null;',
            '',
            '        $nivel_nodo = $nodo->adyacente(\'nivel\');',
            '        if (!$nivel_nodo) {',
            '            $publico = $nodo->adyacente(\'publico\');',
            '            if ($publico) $nivel_nodo = $publico->adyacente(\'nivel\');',
            '        }',
            '        if (!$nivel_nodo || $nivel_nodo->dato() !== \'dueno\') return null;',
            '',
            '        $cont_viajes = $nodo->adyacente(\'viajes\');',
            '        if (!$cont_viajes) {',
            '            $priv = $nodo->adyacente(\'privado\');',
            '            if ($priv) $cont_viajes = $priv->adyacente(\'viajes\');',
            '        }',
            '        if (!$cont_viajes) return null;',
            '',
            '        $terminales = [];',
            '        foreach ((array)$cont_viajes->adyacentes() as $nv => $nodo_viaje) {',
            '            $tas = $nodo_viaje->adyacente(\'terminales_autorizadas\');',
            '            if (!$tas) continue;',
            '            foreach ((array)$tas->adyacentes() as $nombre_t => $nodo_tv) {',
            '                $terminales[(string)$nombre_t] = true;',
            '            }',
            '        }',
            '        foreach (array_keys($terminales) as $nombre_terminal) {',
            '            if (!$nodo->adyacente(\'compartido_con_\' . $nombre_terminal)) {',
            '                $todos_ok = false;',
            '                return null;',
            '            }',
            '        }',
            '        return null;',
            '    }, null);',
            '    return $todos_ok;',
            '}',
            '',
            '/**',
            ' * Aplica la migración de compartidos por terminal.',
            ' *',
            ' * Delega en el comando `app:crear_compartidos_terminal`.',
            ' *',
            ' * @param string $token',
            ' * @return array{exito: bool, detalles: array}',
            ' */',
            'function aplicar_migracion_compartidos_terminal(string $token): array {',
            '    $res = Controlador::ejecutar_comando(\'app:crear_compartidos_terminal\', [\'dueno\' => \'todos\', \'terminal\' => \'todos\']);',
            '    if (!is_array($res)) {',
            '        return [\'exito\' => false, \'detalles\' => [\'El comando no devolvió un resumen válido.\']];',
            '    }',
            '    if (!empty($res[\'errores\'])) {',
            '        return [\'exito\' => false, \'detalles\' => $res];',
            '    }',
            '    return [\'exito\' => true, \'detalles\' => $res];',
            '}',
            '?>',
        ],
    ],

    // ============================================================
    // Aplicacion/Migraciones/Registro.php — entrada nueva
    // ============================================================

    [
        'tipo' => 'reemplazar',
        'archivo' => 'Aplicacion/Migraciones/Registro.php',
        'descripcion' => 'Registro: entrada compartidos_terminal',
        'buscar' => [
            '        \'niveles_usuario\' => [',
            '            \'nombre\' => \'Contenedores publico/privado\',',
            '            \'descripcion\' => \'Crea los contenedores publico y privado en cada usuario.\',',
            '            \'detectar\' => \'detectar_niveles_usuario\',',
            '            \'aplicar\' => \'aplicar_migracion_niveles_usuario\',',
            '        ],',
            '    ];',
        ],
        'reemplazar' => [
            '        \'niveles_usuario\' => [',
            '            \'nombre\' => \'Contenedores publico/privado\',',
            '            \'descripcion\' => \'Crea los contenedores publico y privado en cada usuario.\',',
            '            \'detectar\' => \'detectar_niveles_usuario\',',
            '            \'aplicar\' => \'aplicar_migracion_niveles_usuario\',',
            '        ],',
            '        \'compartidos_terminal\' => [',
            '            \'nombre\' => \'Compartidos por terminal\',',
            '            \'descripcion\' => \'Crea el contenedor compartido_con_us_termX en cada dueño con terminales autorizados.\',',
            '            \'detectar\' => \'detectar_compartidos_terminal\',',
            '            \'aplicar\' => \'aplicar_migracion_compartidos_terminal\',',
            '        ],',
            '    ];',
        ],
    ],

    // ============================================================
    // miscelaneas/migrar_compartidos_terminal.php (nuevo)
    // ============================================================

    [
        'tipo' => 'crear',
        'archivo' => 'miscelaneas/migrar_compartidos_terminal.php',
        'descripcion' => 'Wrapper de migración de compartidos por terminal',
        'contenido' => [
            '<?php',
            '/**',
            ' * Migración Fase B2.1: crear los contenedores',
            ' * `compartido_con_us_termX` en cada dueño.',
            ' *',
            ' * Delega en el comando `app:crear_compartidos_terminal`,',
            ' * que tiene el token encapsulado. No toca los enlaces',
            ' * viejos: los compartidos coexisten con la estructura',
            ' * actual. El código sigue usando la raíz `usuarios`.',
            ' *',
            ' * Idempotente: los compartidos que ya existen se saltean.',
            ' *',
            ' * @since 1.5piloto.76q',
            ' */',
            '',
            'use Iteradores\\Nodos\\Nodo;',
            'use Iteradores\\Controlador\\Controlador;',
            '',
            '/**',
            ' * Ejecuta la migración y guarda si hubo cambios.',
            ' *',
            ' * @return array Resumen.',
            ' */',
            'function migrar_compartidos_terminal(): array {',
            '    $res = Controlador::ejecutar_comando(',
            '        \'app:crear_compartidos_terminal\',',
            '        [\'dueno\' => \'todos\', \'terminal\' => \'todos\']',
            '    );',
            '',
            '    if (!is_array($res)) {',
            '        return [',
            '            \'creados\' => 0,',
            '            \'salteados\' => 0,',
            '            \'errores\' => [\'El comando no devolvió un resumen válido.\'],',
            '        ];',
            '    }',
            '',
            '    if ($res[\'creados\'] > 0) {',
            '        guardar_ambos(ConfiguracionApli::NOMBRE_APP);',
            '    }',
            '',
            '    return $res;',
            '}',
            '?>',
        ],
    ],

    // ============================================================
    // index.php — bloque ?migrar_compartidos_terminal + bump
    // ============================================================

    [
        'tipo' => 'reemplazar',
        'archivo' => 'index.php',
        'descripcion' => 'index.php: bump @version a 1.5piloto.76q',
        'buscar' => [
            ' * @since     1.0.0',
            ' * @version   1.5piloto.76n',
        ],
        'reemplazar' => [
            ' * @since     1.0.0',
            ' * @version   1.5piloto.76q',
        ],
    ],

    [
        'tipo' => 'reemplazar',
        'archivo' => 'index.php',
        'descripcion' => 'index.php: bloque ?migrar_compartidos_terminal',
        'buscar' => [
            '    echo "\\nListo.\\n";',
            '    exit;',
            '}',
            '',
            '// ==== Migración de usuarios a IDs especiales (v76k) ====',
        ],
        'reemplazar' => [
            '    echo "\\nListo.\\n";',
            '    exit;',
            '}',
            '',
            '// ==== Migración de compartidos por terminal (v76q) ====',
            '// Crea los contenedores `compartido_con_us_termX` en',
            '// cada dueño, con referencias filtradas a los viajes,',
            '// empresas, ventas y cancelaciones del terminal. NO',
            '// repunta los accesos viejos: los compartidos coexisten',
            '// con la estructura actual. Idempotente.',
            'if (isset($_GET[\'migrar_compartidos_terminal\'])) {',
            '    header(\'Content-Type: text/plain; charset=utf-8\');',
            '    require_once __DIR__ . \'/miscelaneas/migrar_compartidos_terminal.php\';',
            '    $res = migrar_compartidos_terminal();',
            '    echo "Migración de compartidos por terminal\\n";',
            '    echo "=========================================\\n\\n";',
            '    echo "Creados:   " . $res[\'creados\'] . "\\n";',
            '    echo "Salteados: " . $res[\'salteados\'] . "\\n";',
            '    if (!empty($res[\'errores\'])) {',
            '        echo "Errores:\\n";',
            '        foreach ($res[\'errores\'] as $e) echo "  - $e\\n";',
            '    }',
            '    echo "\\nListo.\\n";',
            '    exit;',
            '}',
            '',
            '// ==== Migración de usuarios a IDs especiales (v76k) ====',
        ],
    ],

    // ============================================================
    // prompts/prompt_piloto.md — plan completo de B2
    // ============================================================

    [
        'tipo' => 'reemplazar',
        'archivo' => 'prompts/prompt_piloto.md',
        'descripcion' => '§8.7: reemplazar "Fases de implementación" con B2.1-4',
        'buscar' => [
            '**Fases de implementación.** El orden revisado es:',
            '',
            '1. Fase A (completada): usuarios como IDs especiales.',
            '2. Fase B1: crear `publico` y `privado` en cada usuario.',
            '   Mover los datos existentes. `usuarios` apunta al',
            '   `publico`. Los `compartido_con_X` todavía no existen.',
            '   Los terminales siguen accediendo como hoy.',
            '3. Fase B2: crear los `compartido_con_X` de cada dueño',
            '   (uno por terminal autorizado) y reescribir los enlaces',
            '   desde los terminales.',
            '4. Fase B3: eliminar los accesos viejos.',
            '5. Fase C: (opcional) tipos como IDs especiales,',
            '   ortogonal.',
            '6. Fase D: aprovechar la carga parcial como optimización.',
            '',
            'Cada fase es una tanda, con migración idempotente y',
            'verificación en local antes de producción.',
        ],
        'reemplazar' => [
            '**Fases de implementación.** El orden revisado es:',
            '',
            '1. **Fase A** (completada en v76k): usuarios como IDs',
            '   especiales (`us_<nombre>`).',
            '2. **Fase B1** (completada en v76m): contenedores',
            '   `publico` y `privado` creados como alias de los',
            '   nodos existentes. Los enlaces viejos quedan vivos.',
            '3. **Fase B2.1** (completada en v76q): crear los',
            '   contenedores `compartido_con_us_termX` en cada dueño,',
            '   con referencias filtradas a los viajes, empresas,',
            '   ventas y cancelaciones del terminal. Alias al',
            '   contenedor de pasajeros del dueño. **No repunta',
            '   nada**: los compartidos coexisten con la estructura',
            '   actual. La migración es idempotente.',
            '4. **Fase B2.2** (pendiente): cambiar el código para que',
            '   el terminal navegue por su compartido. Se agrega un',
            '   parámetro opcional `?Nodo $nodo_contexto` a',
            '   `obtener_contenedor_viajes_dueno`,',
            '   `obtener_contenedor_ventas_dueno` y',
            '   `obtener_contenedor_pasajeros_dueno`. Si el llamador',
            '   pasa el compartido, la función navega desde ahí. Si',
            '   no, navega desde la raíz `usuarios` como hoy.',
            '5. **Fase B2.3** (pendiente): repuntar `us_termX → dueno`',
            '   al contenedor `compartido_con_us_termX`. A partir de',
            '   acá, el acceso del terminal al grafo del dueño pasa',
            '   por la topología.',
            '6. **Fase B2.4** (pendiente): mantener vivos los',
            '   compartidos. Cada operación que modifica viajes',
            '   autorizados, micros, empresas o ventas del terminal',
            '   actualiza el compartido correspondiente.',
            '7. **Fase B3** (pendiente): eliminar los accesos viejos.',
            '8. **Fase C** (opcional): tipos como IDs especiales,',
            '   ortogonal.',
            '9. **Fase D** (pendiente): aprovechar la carga parcial',
            '   como optimización.',
            '',
            '**Comandos asociados.**',
            '',
            '- `app:crear_compartidos_terminal` (v76q): crea los',
            '  compartidos. Args: `{dueno, terminal}`, cada uno',
            '  `nombre` o `todos`. Idempotente.',
            '- Los demás comandos de migración están en el módulo',
            '  `Aplicacion/Migraciones/`. Los tres primeros',
            '  (`grafo:crear_niveles_usuario`, además) son deuda',
            '  técnica: `grafo:crear_niveles_usuario` está en el',
            '  framework pero debería vivir en la app.',
            '',
            'Cada fase es una tanda, con migración idempotente y',
            'verificación en local antes de producción.',
        ],
    ],

    [
        'tipo' => 'reemplazar',
        'archivo' => 'prompts/prompt_piloto.md',
        'descripcion' => 'prompt_piloto: historial v76q',
        'buscar' => [
            '- **v76p**: solo documentación. Se documenta todo el',
        ],
        'reemplazar' => [
            '- **v76q**: Fase B2.1 del modelo topológico. Crea los',
            '  contenedores `compartido_con_us_termX` en cada dueño,',
            '  uno por terminal autorizado en algún viaje del dueño.',
            '  Estructura: `viajes` (solo los autorizados), `empresas`',
            '  (referenciadas por esos viajes), `pasajeros` (alias al',
            '  contenedor del dueño), `ventas` (del terminal),',
            '  `cancelaciones` (del terminal) y `terminales` (solo el',
            '  propio). **No repunta nada**: los compartidos coexisten',
            '  con la estructura actual. La migración es idempotente.',
            '  Nuevo comando `app:crear_compartidos_terminal` en',
            '  `Aplicacion/Migraciones/Comandos.php` (no en el',
            '  `Controlador` del framework, siguiendo la regla de',
            '  v76p). Función `detectar_compartidos_terminal` y',
            '  `aplicar_migracion_compartidos_terminal` en',
            '  `Funciones.php`; entrada `compartidos_terminal` en',
            '  `Registro.php`. Bloque `?migrar_compartidos_terminal=1`',
            '  en `index.php`. Plan completo de B2 (B2.1, B2.2, B2.3,',
            '  B2.4) documentado en §8.7.',
            '- **v76p**: solo documentación. Se documenta todo el',
        ],
    ],

    [
        'tipo' => 'reemplazar',
        'archivo' => 'prompts/prompt_piloto.md',
        'descripcion' => '§12: agregar bullet v76q',
        'buscar' => [
            '- Cerramos en v76n la pestaña Grafo ampliada y el sistema',
        ],
        'reemplazar' => [
            '- Cerramos en v76q la Fase B2.1 del modelo topológico.',
            '  Nuevo comando `app:crear_compartidos_terminal` (en el',
            '  módulo `Aplicacion/Migraciones/`, siguiendo la regla',
            '  de convivencia framework/app). Crea los contenedores',
            '  `compartido_con_us_termX` en cada dueño, con',
            '  referencias filtradas a los viajes autorizados,',
            '  empresas referenciadas por esos viajes, ventas y',
            '  cancelaciones del terminal. Alias al contenedor de',
            '  pasajeros del dueño (mismo nodo físico). **No repunta',
            '  los accesos viejos.** Bloque',
            '  `?migrar_compartidos_terminal=1` en `index.php`.',
            '  Idempotente. Plan completo de B2 (B2.1, B2.2, B2.3,',
            '  B2.4) documentado en §8.7. Pendientes: B2.2 (contexto',
            '  opcional en las funciones de contenedor), B2.3',
            '  (repuntar `us_termX → dueno`), B2.4 (mantener los',
            '  compartidos vivos en cada operación).',
            '- Cerramos en v76n la pestaña Grafo ampliada y el sistema',
        ],
    ],

    [
        'tipo' => 'reemplazar',
        'archivo' => 'prompts/prompt_piloto.md',
        'descripcion' => '§13: estado al cierre a v76q',
        'buscar' => [
            '**Estado del proyecto al cierre:** v1.5piloto.76p (framework 1.5i.7l).',
        ],
        'reemplazar' => [
            '**Estado del proyecto al cierre:** v1.5piloto.76q (framework 1.5i.7l).',
        ],
    ],

    [
        'tipo' => 'reemplazar',
        'archivo' => 'prompts/prompt_piloto.md',
        'descripcion' => '§13: agregar v76q al bloque de estado',
        'buscar' => [
            'v76n: pestaña Grafo con sección "Nodos raíz" y "Migraciones".',
        ],
        'reemplazar' => [
            'v76q: Fase B2.1. Compartidos por terminal creados como',
            'contenedores filtrados en cada dueño. Nuevo comando',
            '`app:crear_compartidos_terminal` en la app. No repunta',
            'nada, coexiste con la estructura actual. Idempotente.',
            'v76n: pestaña Grafo con sección "Nodos raíz" y "Migraciones".',
        ],
    ],

];

// ============================================================
// Runner
// ============================================================
echo "=== Aplicador de cambios ===\n\n";
function detectar_eol(string $c): string { return (strpos($c, "\r\n") !== false) ? "\r\n" : "\n"; }
function normalizar_a_unix(string $c): string { return str_replace("\r\n", "\n", $c); }
function normalizar_a_original(string $c, string $e): string { if ($e === "\n") return $c; return str_replace("\n", "\r\n", $c); }
function contar_ocurrencias(string $c, string $b): int { if ($b === '') return 0; $n = 0; $o = 0; while (($p = strpos($c, $b, $o)) !== false) { $n++; $o = $p + strlen($b); } return $n; }
$creaciones = []; $eliminaciones = []; $reemplazos_por_archivo = [];
foreach ($cambios as $cambio) {
    $tipo = $cambio['tipo'] ?? 'reemplazar';
    if ($tipo === 'crear') { $creaciones[] = $cambio; continue; }
    if ($tipo === 'eliminar') { $eliminaciones[] = $cambio; continue; }
    if (!isset($cambio['archivo']) || !isset($cambio['buscar']) || !isset($cambio['reemplazar'])) { echo "[FALLO] Mal formado.\n"; exit(1); }
    $reemplazos_por_archivo[$cambio['archivo']][] = $cambio;
}
$total_reemplazos = 0;
foreach ($reemplazos_por_archivo as $lista) { $total_reemplazos += count($lista); }
echo "[INFO] $total_reemplazos reemplazo(s) en " . count($reemplazos_por_archivo) . " archivo(s), " . count($creaciones) . " a crear.\n\n";
$archivos_a_escribir = []; $bloques_ok = 0; $bloques_fallidos = [];
foreach ($reemplazos_por_archivo as $archivo_rel => $lista_cambios) {
    $ruta_abs = $raiz_proyecto . '/' . $archivo_rel;
    if (!file_exists($ruta_abs)) { $bloques_fallidos[] = "No encontrado: $archivo_rel"; foreach ($lista_cambios as $c) $bloques_fallidos[] = "  - {$c['descripcion']}"; continue; }
    $contenido_original = file_get_contents($ruta_abs);
    $eol = detectar_eol($contenido_original);
    $contenido = normalizar_a_unix($contenido_original);
    $contenido_antes = $contenido;
    $hubo_error = false;
    foreach ($lista_cambios as $cambio) {
        $buscar_str = implode("\n", $cambio['buscar']);
        $reemplazar_str = implode("\n", $cambio['reemplazar']);
        $ocurrencias = contar_ocurrencias($contenido, $buscar_str);
        if ($ocurrencias === 0) { $bloques_fallidos[] = "$archivo_rel: NO ENCONTRADO - {$cambio['descripcion']}"; $hubo_error = true; continue; }
        if ($ocurrencias > 1) { $bloques_fallidos[] = "$archivo_rel: AMBIGUO ($ocurrencias) - {$cambio['descripcion']}"; $hubo_error = true; continue; }
        $contenido = str_replace($buscar_str, $reemplazar_str, $contenido);
        $bloques_ok++;
    }
    if (!$hubo_error && $contenido !== $contenido_antes) $archivos_a_escribir[$ruta_abs] = normalizar_a_original($contenido, $eol);
}
if ($modo_estricto && !empty($bloques_fallidos)) { echo "=== ABORTADO ===\n"; foreach ($bloques_fallidos as $f) echo "  [FALLO] $f\n"; exit(1); }
foreach ($archivos_a_escribir as $ruta_abs => $contenido_final) {
    if (file_put_contents($ruta_abs, $contenido_final) === false) { echo "[FALLO] Escribir: " . substr($ruta_abs, strlen($raiz_proyecto)+1) . "\n"; continue; }
    echo "[OK] " . substr($ruta_abs, strlen($raiz_proyecto)+1) . "\n";
}
foreach ($creaciones as $c) { $r = $raiz_proyecto.'/'.$c['archivo']; if (!is_dir(dirname($r))) mkdir(dirname($r), 0777, true); if (file_put_contents($r, implode("\n", $c['contenido']))===false){echo "[FALLO] Crear: {$c['archivo']}\n";continue;} echo "[OK] {$c['archivo']} (creado)\n"; }
echo "\n=== Resumen ===\nBloques aplicados: $bloques_ok\nArchivos nuevos:   " . count($creaciones) . "\n";
if (!empty($bloques_fallidos)) { echo "Fallos: " . count($bloques_fallidos) . "\n"; foreach ($bloques_fallidos as $f) echo "  - $f\n"; }
echo "\nListo.\n";